### ISSUE TITLE
Interest in bringing in Buttplug for toy support?

### ISSUE THREAD

**Issue by qdot** [ZengineerVAM/VAMLaunch#1]
Hi! I run https://buttplug.io. Just wanted to offer my help if you're interested in getting more hardware working with VAMLaunch (we already work with ScriptPlayer and provide all non-Launch hardware support for it, and have Launch capabilities built into our libraries). I can also help you with installers/packaging, etc.

Just let me know if you're interested, happy to help however I can (Especially because I was looking at VAM hardware support too, and I'm so happy someone else finished it 'cause my todo list is already too crazy as is :) ).

I'm qdot#0985 on discord, or replying here is fine too.

**Comment by ZengineerVAM** [comment]
We did it! :)
